# Generated by Django 3.2 on 2021-04-27 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raffleticket',
            old_name='draw',
            new_name='luckydraw',
        ),
        migrations.RemoveField(
            model_name='luckydraw',
            name='winner',
        ),
        migrations.AddField(
            model_name='luckydraw',
            name='numberofwinners',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='luckydraw',
            name='winners',
            field=models.ManyToManyField(related_name='winnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='luckydraw',
            name='reward',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='luckydraw',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
