# Generated by Django 3.2 on 2021-04-27 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw', '0002_auto_20210427_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckydraw',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='luckydraws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='luckydraw',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='winnings', to=settings.AUTH_USER_MODEL),
        ),
    ]
